project:
  type: website

website:
  title: "Miguel RC"
  favicon: favicon.ico
  site-url: "https://migue-rc.github.io"
  navbar:
    left:
      - href: index.qmd
        text: "Main"
      - href: about.qmd
        text: "About"
    right:
      - icon: github
        href: https://github.com/migue-rc
      - icon: linkedin
        href: https://linkedin.com/in/rmigue

format:
  html:
    theme:
      light: sketchy
      dark: [sketchy, sketchy-dark.scss]
    css: brand-theme.css 
    toc: true
